////
Copyright 2021 Michael Brohl

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
= Parametric Bonsai Nebari Groundplate

OpenSCAD (https://www.openscad.org) file to generate a circular platform of defined diameter.
If printed in PLA (https://en.wikipedia.org/wiki/Polylactic_acid), it will be an ecological and biodegradable tool to optimize your bonsai root development.
It has been designed with the aim of educating the radial growth of the roots avoiding entanglements between them and a balanced distribution to obtain the best nebari of your future bonsai.
The spaced and concentric divisions provide a correct channeling of root growth.
It should be used buried a few centimeters from the surface with the future bonsai fixed in its center, leaving a couple of centimeters at least from the edge of the platform to the wall of the pot to facilitate the descent of the roots in search of nutrients.
In this way you will obtain a perfect nebari and a balanced radial distribution of the roots when growing on the platform in search of the edge and the lower substrate.

== How to print

Open the OpenSCAD .scad file in OpenSCAD and adjust the marked parameters.
Render the object and then export as STL to use it in your slicer software.
